version: '3.8'
services:
  web:
    image: harbor.internal/el-dorado/web:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - OTEL_SERVICE_NAME=edge-nginx
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.1.40:4318/v1/traces
    depends_on:
      - server
    networks:
      - el-dorado-net

  server:
    image: harbor.internal/el-dorado/server:latest
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - OTEL_SERVICE_NAME=node-backend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.1.40:4318/v1/traces
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - el-dorado-net

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=el_dorado
      - POSTGRES_USER=postgres
      # POSTGRES_PASSWORD should be set in Coolify environment variables/secrets
    networks:
      - el-dorado-net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - el-dorado-net

networks:
  el-dorado-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:

